export type CityFaq = {
  question: string;
  answer: string;
};

export type CityPageData = {
  slug: string;
  name: string;
  preposition: "de" | "do";
  intro: string;
  localHeading: string;
  localContext: string;
  welcomeHeading: string;
  welcomeText: string;
  dependencyHeading: string;
  dependencyText: string;
  alcoholHeading: string;
  alcoholText: string;
  familyHeading: string;
  familyText: string;
  contactHeading: string;
  contactText: string;
  seoDescription: string;
  relatedSlugs: string[];
  faqs: CityFaq[];
};

export const cityPages: CityPageData[] = [
  {
    slug: "sao-carlos-sp",
    name: "São Carlos",
    preposition: "de",
    intro: "Para famílias de São Carlos que enfrentam dificuldades relacionadas ao álcool ou a outras drogas, ter uma conversa clara pode ajudar a organizar as dúvidas antes de qualquer decisão.",
    localHeading: "Orientação para famílias de São Carlos",
    localContext: "A Central mantém sua unidade física em Araraquara. Pessoas e famílias de São Carlos podem entrar em contato para entender a proposta de acolhimento, verificar as condições disponíveis e avaliar os próximos passos com responsabilidade.",
    welcomeHeading: "Acolhimento com informação desde o primeiro contato",
    welcomeText: "O contato inicial é um espaço para relatar a situação e conhecer como o acolhimento é conduzido. Nenhuma decisão precisa ser tomada sem que a família compreenda as etapas e esclareça suas principais dúvidas.",
    dependencyHeading: "Dependência química: compreender a situação antes de agir",
    dependencyText: "Mudanças de comportamento, prejuízos nos vínculos e dificuldade de interromper o uso podem mobilizar toda a família. Uma avaliação individual ajuda a identificar necessidades e possibilidades de cuidado, sem fórmulas prontas.",
    alcoholHeading: "Quando o consumo de álcool passa a preocupar",
    alcoholText: "O álcool pode afetar rotina, saúde e relações de maneiras diferentes. Famílias de São Carlos podem buscar orientação para compreender o processo de acolhimento na unidade de Araraquara e saber quais informações serão necessárias.",
    familyHeading: "Como a família pode começar essa conversa",
    familyText: "Reunir informações objetivas sobre o que vem acontecendo ajuda no primeiro atendimento. A equipe escuta o contexto, responde perguntas e apresenta caminhos possíveis, respeitando os limites de cada situação.",
    contactHeading: "Converse com a Central a partir de São Carlos",
    contactText: "O atendimento começa por WhatsApp ou telefone. A equipe explica que a unidade fica em Araraquara e informa, conforme avaliação e disponibilidade, como pode ocorrer o acolhimento.",
    seoDescription: "Orientação para famílias de São Carlos que buscam acolhimento para dependência química e alcoolismo na unidade da Central em Araraquara.",
    relatedSlugs: ["ibate-sp", "descalvado-sp"],
    faqs: [
      { question: "Existe uma unidade da Central em São Carlos?", answer: "Não. A unidade física da Central de Acolhimento e Reabilitação fica em Araraquara. Esta página orienta famílias de São Carlos que desejam conhecer as possibilidades de acolhimento nessa unidade." },
      { question: "Como uma família de São Carlos pode pedir orientação?", answer: "O primeiro contato pode ser feito por WhatsApp ou telefone. A família relata a situação e recebe informações sobre avaliação, disponibilidade e etapas do acolhimento." },
      { question: "O acolhimento é indicado para qualquer caso de uso de drogas?", answer: "Não existe indicação automática. Cada situação precisa ser compreendida individualmente e avaliada segundo as necessidades da pessoa e as condições aplicáveis." },
      { question: "Como conversar sobre problemas com álcool?", answer: "A conversa deve evitar julgamentos e priorizar fatos observados. A equipe pode orientar a família sobre como apresentar o contexto no contato inicial." },
    ],
  },
  {
    slug: "rio-claro-sp",
    name: "Rio Claro",
    preposition: "de",
    intro: "Quem vive em Rio Claro e percebe que o uso de substâncias está comprometendo a vida familiar pode procurar informação antes de definir qualquer medida. A escuta inicial ajuda a tornar esse momento menos confuso.",
    localHeading: "Um ponto de apoio para quem procura ajuda em Rio Claro",
    localContext: "A Central de Acolhimento e Reabilitação está fisicamente localizada em Araraquara. A equipe recebe contatos de Rio Claro e explica as possibilidades de atendimento na unidade, sempre sujeitas à avaliação e à disponibilidade.",
    welcomeHeading: "Acolhimento pensado a partir da realidade de cada pessoa",
    welcomeText: "A proposta de acolhimento é apresentada com clareza para que a pessoa e seus familiares entendam rotina, responsabilidades e condições. O processo não começa com promessas, mas com escuta e informação.",
    dependencyHeading: "Orientação diante do uso persistente de drogas",
    dependencyText: "A dependência química envolve fatores pessoais, familiares e sociais. Por isso, a situação deve ser analisada de modo individual, considerando o histórico e as necessidades relatadas no contato.",
    alcoholHeading: "Ajuda quando o álcool interfere na vida cotidiana",
    alcoholText: "Conflitos frequentes, perdas de compromisso e dificuldade de reduzir o consumo podem indicar que é hora de buscar orientação. A família pode conhecer as condições de acolhimento oferecidas em Araraquara.",
    familyHeading: "A família também precisa ser ouvida",
    familyText: "Dúvidas, medo e cansaço são comuns quando o problema se prolonga. O atendimento inicial permite organizar informações e compreender o que pode ou não ser feito em cada circunstância.",
    contactHeading: "Informações para moradores de Rio Claro",
    contactText: "Pelo WhatsApp ou telefone, a família pode explicar o que está acontecendo e perguntar sobre a unidade de Araraquara. A equipe orienta os próximos passos sem garantir indicação ou vaga antes da avaliação.",
    seoDescription: "Famílias de Rio Claro podem buscar orientação sobre dependência química, alcoolismo e acolhimento na unidade física da Central em Araraquara.",
    relatedSlugs: ["sao-carlos-sp", "porto-ferreira-sp"],
    faqs: [
      { question: "A Central possui clínica em Rio Claro?", answer: "Não. A unidade física fica em Araraquara. A Central pode orientar famílias de Rio Claro interessadas em conhecer o acolhimento realizado nessa unidade." },
      { question: "É possível tirar dúvidas antes de decidir?", answer: "Sim. O contato inicial serve para apresentar a situação, compreender o funcionamento e verificar as condições, sem obrigação de prosseguir." },
      { question: "Como funciona a orientação sobre alcoolismo?", answer: "A família relata os impactos observados e recebe informações gerais sobre acolhimento e avaliação. Não há promessa de prazo ou resultado." },
      { question: "Há garantia de acolhimento para quem vem de Rio Claro?", answer: "Não. Toda possibilidade depende de avaliação individual, disponibilidade e condições informadas pela equipe." },
    ],
  },
  {
    slug: "bauru-sp",
    name: "Bauru",
    preposition: "de",
    intro: "Famílias de Bauru que procuram um caminho diante da dependência química podem iniciar pela informação. Entender o acolhimento, seus limites e suas etapas ajuda a tomar decisões mais conscientes.",
    localHeading: "Atendimento inicial para famílias de Bauru",
    localContext: "Não há unidade da Central em Bauru. A estrutura física fica em Araraquara e pode receber pessoas de outras cidades quando a avaliação, a disponibilidade e as condições do acolhimento permitirem.",
    welcomeHeading: "O que considerar ao buscar acolhimento fora da cidade",
    welcomeText: "Além das necessidades da pessoa, a família precisa compreender a localização da unidade, as etapas de entrada e a forma de acompanhamento. Esses pontos são apresentados antes de qualquer encaminhamento.",
    dependencyHeading: "Dependência química exige uma análise cuidadosa",
    dependencyText: "O uso problemático não se manifesta do mesmo modo em todas as pessoas. Histórico, condições de saúde, rede familiar e momento atual precisam ser considerados para orientar uma possibilidade de cuidado.",
    alcoholHeading: "Orientação para situações relacionadas ao alcoolismo",
    alcoholText: "Quando o consumo de álcool gera prejuízos repetidos, buscar uma conversa profissional pode ajudar a família a compreender alternativas. O acolhimento não é apresentado como resposta automática para todos os casos.",
    familyHeading: "Preparar a família para os próximos passos",
    familyText: "A equipe pode explicar quais informações são importantes e como ocorre a conversa inicial. Essa organização é especialmente útil para quem está em Bauru e avalia uma unidade localizada em outra cidade.",
    contactHeading: "Como falar com a Central estando em Bauru",
    contactText: "O contato remoto por WhatsApp ou telefone permite esclarecer localização, disponibilidade e processo. Se houver possibilidade de acolhimento, os procedimentos necessários são combinados com antecedência.",
    seoDescription: "Orientação a famílias de Bauru sobre acolhimento para dependência química e alcoolismo na unidade física da Central em Araraquara.",
    relatedSlugs: ["ibitinga-sp", "ribeirao-preto-sp"],
    faqs: [
      { question: "A Central de Acolhimento fica em Bauru?", answer: "Não. A unidade física fica em Araraquara. Famílias de Bauru podem entrar em contato para verificar se o acolhimento nessa unidade é uma possibilidade." },
      { question: "Como avaliar uma opção de acolhimento em outra cidade?", answer: "É importante conhecer localização, proposta, etapas, condições e forma de contato com a família. A equipe esclarece esses pontos antes de qualquer decisão." },
      { question: "A dependência química sempre exige internação?", answer: "Não. Cada situação precisa de avaliação individual. A internação não deve ser tratada como solução automática." },
      { question: "Posso ligar apenas para obter informações?", answer: "Sim. O telefone e o WhatsApp estão disponíveis para uma conversa inicial e esclarecimento de dúvidas." },
    ],
  },
  {
    slug: "ribeirao-preto-sp",
    name: "Ribeirão Preto",
    preposition: "de",
    intro: "Para uma família de Ribeirão Preto, procurar acolhimento em outra cidade costuma trazer perguntas práticas e emocionais. A Central oferece um primeiro contato para explicar com transparência o que pode ser avaliado.",
    localHeading: "Orientação a partir de Ribeirão Preto",
    localContext: "A Central não possui filial em Ribeirão Preto. Sua unidade física está em Araraquara e recebe consultas de famílias de diferentes municípios, sem garantia prévia de acolhimento.",
    welcomeHeading: "Informações claras para avaliar o acolhimento",
    welcomeText: "Antes de seguir, a família conhece as etapas, apresenta o contexto e recebe orientações sobre as condições da unidade. A distância entre as cidades torna esse alinhamento inicial ainda mais importante.",
    dependencyHeading: "Cuidado diante da dependência química",
    dependencyText: "A situação pode envolver perdas na rotina, conflitos e dificuldade de manter escolhas. O acolhimento é uma possibilidade que precisa ser analisada com responsabilidade, respeitando a pessoa e sua história.",
    alcoholHeading: "Quando a família busca ajuda para alcoolismo",
    alcoholText: "O impacto do álcool pode crescer gradualmente e nem sempre é simples reconhecer quando pedir ajuda. A equipe escuta o relato e informa como funciona a avaliação para a unidade de Araraquara.",
    familyHeading: "Decisões familiares sem pressão ou sensacionalismo",
    familyText: "O objetivo do primeiro atendimento é esclarecer, não pressionar. A família pode perguntar sobre procedimentos, limites e disponibilidade antes de considerar qualquer deslocamento.",
    contactHeading: "Primeiro contato para quem está em Ribeirão Preto",
    contactText: "WhatsApp e telefone permitem iniciar a conversa sem sair da cidade. Caso exista indicação e possibilidade, a equipe combina os próximos passos de forma organizada.",
    seoDescription: "Informações para famílias de Ribeirão Preto que avaliam acolhimento para dependência química ou alcoolismo na Central em Araraquara.",
    relatedSlugs: ["franca-sp", "jaboticabal-sp"],
    faqs: [
      { question: "Existe unidade da Central em Ribeirão Preto?", answer: "Não. A unidade física da Central está localizada em Araraquara e não há afirmação de filial em Ribeirão Preto." },
      { question: "É preciso viajar antes de obter informações?", answer: "Não. A conversa inicial pode ocorrer por WhatsApp ou telefone para que a família esclareça as condições antes de qualquer deslocamento." },
      { question: "Como é analisada uma situação de alcoolismo?", answer: "O relato e as necessidades são considerados individualmente. A equipe não oferece diagnóstico pelo site nem garante que o acolhimento será indicado." },
      { question: "A disponibilidade pode ser confirmada no primeiro contato?", answer: "A equipe verifica a situação apresentada e as condições do momento. Não há garantia prévia de vaga ou atendimento." },
    ],
  },
  {
    slug: "matao-sp",
    name: "Matão",
    preposition: "de",
    intro: "Quando uma família de Matão percebe que não consegue mais lidar sozinha com o uso de álcool ou drogas, uma orientação inicial pode ajudar a separar urgências, dúvidas e possibilidades.",
    localHeading: "Famílias de Matão podem conversar com a Central",
    localContext: "A unidade física está em Araraquara, não em Matão. A proximidade regional permite que famílias façam contato para conhecer o processo, sempre conforme avaliação, disponibilidade e condições de acolhimento.",
    welcomeHeading: "Acolhimento começa pela escuta da situação",
    welcomeText: "Cada contato traz uma história diferente. A equipe procura entender o momento vivido, explicar a proposta da unidade e evitar decisões baseadas apenas no medo ou na pressa.",
    dependencyHeading: "Sinais de que o uso de drogas merece atenção",
    dependencyText: "Rompimento de vínculos, abandono de compromissos e repetição de situações de risco podem preocupar. Esses sinais não substituem uma avaliação, mas justificam a busca por informação responsável.",
    alcoholHeading: "Problemas com álcool dentro da rotina familiar",
    alcoholText: "O consumo pode gerar conflitos silenciosos e desgaste prolongado. A família pode relatar o que observa e conhecer as possibilidades de cuidado disponíveis na unidade de Araraquara.",
    familyHeading: "Orientar sem culpabilizar",
    familyText: "A conversa com familiares busca organizar fatos e dúvidas sem transformar culpa em resposta. O papel da equipe é apresentar o processo e indicar o que precisa ser avaliado.",
    contactHeading: "Contato direto para moradores de Matão",
    contactText: "Ligue ou envie uma mensagem para explicar a situação. A equipe informa como funciona o acolhimento em Araraquara e, se for possível avançar, combina as etapas seguintes.",
    seoDescription: "Famílias de Matão encontram orientação sobre dependência química, alcoolismo e acolhimento na unidade da Central localizada em Araraquara.",
    relatedSlugs: ["taquaritinga-sp", "jaboticabal-sp"],
    faqs: [
      { question: "Há uma clínica da Central em Matão?", answer: "Não. A Central possui unidade física em Araraquara. Moradores de Matão podem pedir informações sobre o acolhimento realizado lá." },
      { question: "O que contar no primeiro contato?", answer: "A família pode descrever mudanças observadas, histórico conhecido, situação atual e principais dúvidas. A equipe indicará outras informações necessárias." },
      { question: "Buscar ajuda significa decidir pela internação?", answer: "Não. Pedir orientação não obriga a família a seguir com acolhimento ou internação. A situação deve ser avaliada." },
      { question: "Como falar com a equipe?", answer: "O contato pode ser feito pelo WhatsApp ou pelo telefone informado nesta página." },
    ],
  },
  {
    slug: "americo-brasiliense-sp",
    name: "Américo Brasiliense",
    preposition: "de",
    intro: "Famílias de Américo Brasiliense que precisam de orientação sobre álcool e outras drogas podem conversar diretamente com a Central e conhecer uma possibilidade de acolhimento na cidade vizinha de Araraquara.",
    localHeading: "Orientação próxima, com unidade em Araraquara",
    localContext: "A Central não mantém unidade em Américo Brasiliense. O atendimento físico acontece em Araraquara, e o primeiro contato esclarece avaliação, disponibilidade e condições para pessoas vindas da região.",
    welcomeHeading: "Conheça o processo antes de decidir",
    welcomeText: "A equipe apresenta as etapas do acolhimento e ouve as informações da família. Esse diálogo permite compreender se há condições para prosseguir e quais procedimentos seriam necessários.",
    dependencyHeading: "Quando o uso de drogas afeta toda a casa",
    dependencyText: "A dependência química pode alterar confiança, rotina e convivência. Procurar apoio não significa encontrar uma resposta imediata, mas pode ajudar a construir uma decisão mais informada.",
    alcoholHeading: "Atenção aos impactos do consumo de álcool",
    alcoholText: "Quando o álcool provoca prejuízos repetidos, a família pode buscar esclarecimentos sobre acolhimento. Cada pessoa, porém, deve ser considerada de forma individual.",
    familyHeading: "Um primeiro passo acessível para a família",
    familyText: "Por estar na mesma região, a família pode iniciar a conversa por telefone e compreender o funcionamento da unidade antes de organizar qualquer procedimento presencial.",
    contactHeading: "Fale com a equipe a partir de Américo Brasiliense",
    contactText: "Use o WhatsApp para enviar uma mensagem ou ligue diretamente. A equipe responderá sobre o processo em Araraquara sem criar expectativa de resultado ou admissão automática.",
    seoDescription: "Orientação para famílias de Américo Brasiliense sobre acolhimento para álcool e drogas na unidade da Central localizada em Araraquara.",
    relatedSlugs: ["sao-carlos-sp", "matao-sp"],
    faqs: [
      { question: "A unidade fica em Américo Brasiliense?", answer: "Não. A unidade física da Central fica em Araraquara. Esta página atende à busca de famílias de Américo Brasiliense por orientação." },
      { question: "Posso conhecer o processo antes de ir à unidade?", answer: "Sim. A equipe explica por telefone ou WhatsApp as etapas e condições iniciais antes de qualquer procedimento presencial." },
      { question: "Como a família pode ajudar sem discutir?", answer: "É útil escolher um momento seguro, falar sobre fatos concretos e evitar ameaças. A orientação profissional pode apoiar a organização dos próximos passos." },
      { question: "O acolhimento depende de disponibilidade?", answer: "Sim. Além da avaliação individual, é necessário confirmar disponibilidade e demais condições com a equipe." },
    ],
  },
  {
    slug: "taquaritinga-sp",
    name: "Taquaritinga",
    preposition: "de",
    intro: "Em Taquaritinga, muitas famílias começam a procurar ajuda quando os conflitos e as preocupações já se acumulam. Uma conversa inicial pode transformar informações dispersas em perguntas mais objetivas.",
    localHeading: "Caminhos de orientação para Taquaritinga",
    localContext: "A Central está localizada em Araraquara e não possui unidade física em Taquaritinga. Famílias da cidade podem consultar a equipe sobre a possibilidade de acolhimento na unidade principal.",
    welcomeHeading: "Acolhimento avaliado caso a caso",
    welcomeText: "Não existe um procedimento idêntico para todas as pessoas. O histórico, as condições atuais e a possibilidade de participação no processo precisam ser considerados antes de qualquer encaminhamento.",
    dependencyHeading: "Entendendo os impactos da dependência química",
    dependencyText: "O uso continuado pode comprometer escolhas, trabalho, estudos e relações. A orientação ajuda a família a compreender que cuidado responsável exige avaliação, e não apenas uma decisão tomada em momento de crise.",
    alcoholHeading: "Quando o alcoolismo se torna uma preocupação familiar",
    alcoholText: "A frequência de consumo não é o único aspecto relevante; os prejuízos e a dificuldade de mudar também precisam ser observados. O contato permite esclarecer como esses dados entram na avaliação.",
    familyHeading: "Informação para reduzir decisões impulsivas",
    familyText: "Mesmo em situações desgastantes, é importante evitar iniciativas por conta própria. A equipe orienta sobre procedimentos aplicáveis e sobre os limites do acolhimento.",
    contactHeading: "Orientação por telefone para Taquaritinga",
    contactText: "A família pode ligar ou usar o WhatsApp para apresentar o contexto. Se houver possibilidade de seguir, serão explicados os procedimentos relacionados à unidade de Araraquara.",
    seoDescription: "Informações para famílias de Taquaritinga sobre dependência química, alcoolismo e possível acolhimento na unidade da Central em Araraquara.",
    relatedSlugs: ["matao-sp", "jaboticabal-sp"],
    faqs: [
      { question: "Existe unidade física em Taquaritinga?", answer: "Não. A unidade da Central de Acolhimento e Reabilitação está em Araraquara." },
      { question: "A família pode pedir orientação sem a pessoa presente?", answer: "A família pode fazer o contato inicial e relatar o contexto. A equipe explicará quais participações e avaliações serão necessárias depois." },
      { question: "Como funciona a avaliação para acolhimento?", answer: "A situação é analisada individualmente a partir das informações disponíveis e das condições aplicáveis. A avaliação não garante admissão." },
      { question: "Há prazo fixo de tratamento?", answer: "Não. Duração e acompanhamento dependem das necessidades e da evolução de cada pessoa, sem promessa de prazo ou resultado." },
    ],
  },
  {
    slug: "ibitinga-sp",
    name: "Ibitinga",
    preposition: "de",
    intro: "Para quem está em Ibitinga, avaliar acolhimento em Araraquara exige informações seguras sobre o processo. A família pode esclarecer suas dúvidas à distância antes de considerar os próximos passos.",
    localHeading: "Informações para famílias de Ibitinga",
    localContext: "A Central não possui estrutura física em Ibitinga. Sua unidade fica em Araraquara e pode analisar contatos de outras cidades conforme as necessidades apresentadas, a disponibilidade e as condições do serviço.",
    welcomeHeading: "Planejamento antes de um possível acolhimento",
    welcomeText: "Quando há deslocamento entre cidades, alinhar informações evita expectativas incorretas. A conversa aborda a situação, o funcionamento da unidade e o que precisa ser confirmado antes de avançar.",
    dependencyHeading: "Dependência química e mudanças que preocupam",
    dependencyText: "Isolamento, instabilidade e repetição de comportamentos prejudiciais podem levar a família a procurar ajuda. Esses aspectos precisam ser relatados com cuidado e avaliados individualmente.",
    alcoholHeading: "Consumo de álcool e perda de autonomia",
    alcoholText: "A dificuldade de controlar o consumo pode afetar decisões e relações. A equipe pode orientar sobre a proposta de acolhimento sem afirmar que ela será adequada a toda situação.",
    familyHeading: "Apoio para organizar dúvidas e informações",
    familyText: "Antes de ligar, a família pode reunir um breve histórico e anotar perguntas. Isso torna o primeiro contato mais claro e facilita a explicação das condições disponíveis.",
    contactHeading: "Comece pelo WhatsApp ou telefone",
    contactText: "Moradores de Ibitinga podem falar com a equipe sem deslocamento inicial. Havendo possibilidade de acolhimento, os detalhes da unidade em Araraquara são combinados diretamente.",
    seoDescription: "Famílias de Ibitinga podem conhecer o acolhimento para dependência química e alcoolismo realizado na unidade da Central em Araraquara.",
    relatedSlugs: ["itapolis-sp", "bauru-sp"],
    faqs: [
      { question: "A Central tem unidade em Ibitinga?", answer: "Não. A unidade física está em Araraquara. O site oferece esta página para orientar famílias de Ibitinga sobre essa possibilidade." },
      { question: "Como obter informações sem viajar?", answer: "WhatsApp e telefone permitem conversar com a equipe, descrever a situação e conhecer as condições iniciais." },
      { question: "O acolhimento é confirmado pela internet?", answer: "Não. O site oferece informação e contato. Qualquer possibilidade depende de conversa, avaliação, disponibilidade e procedimentos adequados." },
      { question: "Quanto tempo dura o acompanhamento?", answer: "Não há duração única. O período depende das necessidades e deve ser reavaliado, sem garantias antecipadas." },
    ],
  },
  {
    slug: "itapolis-sp",
    name: "Itápolis",
    preposition: "de",
    intro: "Uma família de Itápolis pode ter dificuldade para saber a quem recorrer quando o uso de drogas ou álcool passa a dominar a rotina. Buscar orientação é uma forma de conhecer opções sem assumir compromissos precipitados.",
    localHeading: "Orientação responsável para moradores de Itápolis",
    localContext: "A unidade da Central está em Araraquara. Não existe filial informada em Itápolis; há, porém, atendimento inicial a famílias da região interessadas em avaliar o acolhimento na unidade principal.",
    welcomeHeading: "Escuta inicial e explicação das condições",
    welcomeText: "A equipe ouve o contexto e esclarece como funciona a análise. São considerados tanto as necessidades da pessoa quanto os limites, a disponibilidade e os procedimentos do acolhimento.",
    dependencyHeading: "Quando a dependência muda prioridades e vínculos",
    dependencyText: "O problema pode aparecer em faltas, afastamento familiar, dívidas ou situações de risco. Nenhum sinal isolado define uma conduta, mas o conjunto pode indicar a necessidade de procurar avaliação.",
    alcoholHeading: "Alcoolismo: cuidado sem rótulos ou promessas",
    alcoholText: "Falar de alcoolismo exige respeito e atenção ao impacto real do consumo. A família pode pedir informações sobre acolhimento sem receber garantias simplistas de cura.",
    familyHeading: "O papel da família no contato inicial",
    familyText: "A família ajuda ao compartilhar informações honestas e ouvir as orientações. Não é recomendado organizar uma internação por conta própria ou sem os critérios necessários.",
    contactHeading: "Fale com a unidade de Araraquara a partir de Itápolis",
    contactText: "A conversa pode começar por mensagem ou ligação. A equipe informa se é possível avaliar o caso e quais seriam os passos seguintes.",
    seoDescription: "Orientação para moradores de Itápolis sobre dependência química, alcoolismo e acolhimento na unidade física da Central em Araraquara.",
    relatedSlugs: ["ibitinga-sp", "taquaritinga-sp"],
    faqs: [
      { question: "Existe uma filial da Central em Itápolis?", answer: "Não. A única unidade física informada fica em Araraquara. Famílias de Itápolis podem entrar em contato para conhecer essa estrutura." },
      { question: "Quais informações ajudam na conversa inicial?", answer: "Histórico conhecido, situação atual, impactos na rotina e dúvidas da família ajudam a equipe a compreender o contexto." },
      { question: "A internação involuntária é uma solução automática?", answer: "Não. Ela exige avaliação responsável, indicação profissional e cumprimento da legislação aplicável. Cada situação é individual." },
      { question: "O primeiro contato tem compromisso?", answer: "Não. A conversa inicial serve para orientação e esclarecimento das possibilidades." },
    ],
  },
  {
    slug: "ibate-sp",
    name: "Ibaté",
    preposition: "de",
    intro: "Famílias de Ibaté que convivem com o uso problemático de álcool ou drogas podem buscar uma conversa próxima e objetiva sobre acolhimento na unidade localizada em Araraquara.",
    localHeading: "Acolhimento em Araraquara para quem vem de Ibaté",
    localContext: "A Central não possui unidade em Ibaté. A equipe atende contatos da cidade e explica as condições para uma possível entrada na estrutura física de Araraquara.",
    welcomeHeading: "Proximidade não dispensa avaliação",
    welcomeText: "Mesmo para cidades próximas, o acolhimento precisa ser organizado com antecedência. A família apresenta a situação, conhece a proposta e confirma se existe disponibilidade e possibilidade de seguir.",
    dependencyHeading: "Ajuda diante do uso problemático de substâncias",
    dependencyText: "A perda de controle e os prejuízos recorrentes podem sinalizar uma situação complexa. O cuidado deve considerar a pessoa como um todo, e não somente a substância utilizada.",
    alcoholHeading: "Orientação para famílias afetadas pelo álcool",
    alcoholText: "O sofrimento familiar merece ser ouvido, mas a decisão sobre acolhimento deve ser responsável. A Central explica seu processo e os critérios que precisam ser observados.",
    familyHeading: "Uma conversa para compreender alternativas",
    familyText: "O contato permite que a família faça perguntas e entenda a diferença entre pedir informação e confirmar um acolhimento. Cada etapa é tratada separadamente.",
    contactHeading: "Contato rápido para famílias de Ibaté",
    contactText: "WhatsApp e ligação estão disponíveis para o atendimento inicial. Se o acolhimento for considerado possível, a equipe orienta sobre a chegada à unidade de Araraquara.",
    seoDescription: "Famílias de Ibaté podem pedir orientação sobre álcool, drogas e acolhimento na unidade da Central de Acolhimento em Araraquara.",
    relatedSlugs: ["sao-carlos-sp", "descalvado-sp"],
    faqs: [
      { question: "A Central está localizada em Ibaté?", answer: "Não. A unidade física fica em Araraquara. Famílias de Ibaté podem consultar a equipe sobre o acolhimento nessa unidade." },
      { question: "A proximidade garante uma vaga?", answer: "Não. A cidade de origem não garante acolhimento. É necessário avaliar a situação e confirmar disponibilidade e condições." },
      { question: "Posso falar sobre um familiar pelo WhatsApp?", answer: "Sim. O contato inicial pode apresentar a situação de forma resumida; a equipe indicará como aprofundar as informações com privacidade." },
      { question: "Há promessa de recuperação?", answer: "Não. O cuidado depende de diversos fatores e não é responsável prometer cura ou resultado." },
    ],
  },
  {
    slug: "descalvado-sp",
    name: "Descalvado",
    preposition: "de",
    intro: "Quem procura ajuda em Descalvado pode começar entendendo quais alternativas existem e como funciona uma avaliação. A Central oferece orientação sobre sua unidade física em Araraquara.",
    localHeading: "Informação para famílias de Descalvado",
    localContext: "A Central de Acolhimento e Reabilitação não possui unidade em Descalvado. Famílias da cidade podem entrar em contato para avaliar, sem garantia prévia, uma possibilidade de acolhimento em Araraquara.",
    welcomeHeading: "Acolhimento com etapas explicadas à família",
    welcomeText: "O processo começa com informações sobre o momento atual. Em seguida, a equipe esclarece sua forma de trabalho, o que precisa ser avaliado e quais condições devem existir para avançar.",
    dependencyHeading: "Dependência química e necessidade de apoio",
    dependencyText: "Tentar resolver o problema apenas com cobranças pode aumentar o desgaste. Uma orientação adequada ajuda a família a compreender limites e a procurar uma avaliação compatível com a situação.",
    alcoholHeading: "Quando as consequências do álcool se repetem",
    alcoholText: "Acidentes, conflitos e descumprimento de compromissos podem indicar prejuízos importantes. O relato deve ser analisado sem julgamentos e sem transformar acolhimento em resposta obrigatória.",
    familyHeading: "Cuidar também da forma de tomar decisões",
    familyText: "A família pode se preparar anotando fatos, dúvidas e tentativas anteriores de ajuda. Isso favorece uma conversa mais objetiva com a equipe.",
    contactHeading: "Como solicitar orientação em Descalvado",
    contactText: "Envie uma mensagem ou ligue para a Central. A equipe explica o atendimento em Araraquara e informa o que pode ser feito a partir do contexto apresentado.",
    seoDescription: "Orientação a famílias de Descalvado que procuram acolhimento para dependência química e alcoolismo na unidade da Central em Araraquara.",
    relatedSlugs: ["porto-ferreira-sp", "sao-carlos-sp"],
    faqs: [
      { question: "Há unidade da Central em Descalvado?", answer: "Não. A unidade física está em Araraquara. O contato de famílias de Descalvado é feito para conhecer essa possibilidade." },
      { question: "Como saber se é hora de pedir ajuda?", answer: "Prejuízos repetidos, situações de risco e dificuldade de mudança justificam buscar orientação. A definição de cuidado depende de avaliação." },
      { question: "A família deve levar a pessoa diretamente?", answer: "Não é indicado realizar procedimentos por conta própria. Primeiro converse com a equipe e confirme avaliação, disponibilidade e orientações." },
      { question: "O telefone funciona para dúvidas iniciais?", answer: "Sim. A família pode ligar para esclarecer o processo antes de qualquer decisão." },
    ],
  },
  {
    slug: "porto-ferreira-sp",
    name: "Porto Ferreira",
    preposition: "de",
    intro: "Para famílias de Porto Ferreira, conhecer uma opção de acolhimento em Araraquara pode começar com perguntas simples: como funciona, o que é avaliado e quais condições precisam ser atendidas.",
    localHeading: "Orientação para Porto Ferreira com transparência",
    localContext: "A unidade física da Central fica em Araraquara. Não existe unidade própria informada em Porto Ferreira, e todo possível acolhimento deve ser consultado previamente.",
    welcomeHeading: "Uma conversa antes de organizar o deslocamento",
    welcomeText: "A equipe orienta a família remotamente para evitar viagens sem confirmação. São explicadas as etapas iniciais e verificada a possibilidade de continuidade.",
    dependencyHeading: "Dependência química e escolhas de cuidado",
    dependencyText: "Buscar acolhimento é uma decisão relevante e não deve se apoiar em soluções rápidas. A análise considera necessidades, contexto familiar e condições que possam interferir no processo.",
    alcoholHeading: "Ajuda para situações de uso prejudicial de álcool",
    alcoholText: "Quando tentativas de mudança não se sustentam e os prejuízos aumentam, a família pode procurar orientação. Isso não significa que uma modalidade específica será indicada.",
    familyHeading: "Perguntas importantes para a família fazer",
    familyText: "É válido perguntar sobre localização, rotina, comunicação, critérios e etapas. Informações claras ajudam moradores de Porto Ferreira a decidir se devem continuar a avaliação.",
    contactHeading: "Fale com a unidade de Araraquara",
    contactText: "O WhatsApp e o telefone permitem iniciar o atendimento. Se houver indicação, disponibilidade e condições, a equipe combina os procedimentos necessários.",
    seoDescription: "Famílias de Porto Ferreira encontram informações sobre acolhimento para álcool e drogas na unidade física da Central em Araraquara.",
    relatedSlugs: ["descalvado-sp", "rio-claro-sp"],
    faqs: [
      { question: "Existe unidade da Central em Porto Ferreira?", answer: "Não. A unidade física fica em Araraquara. Esta página esclarece a famílias de Porto Ferreira como consultar essa possibilidade." },
      { question: "Preciso agendar antes de ir?", answer: "A família deve entrar em contato antes de qualquer deslocamento para apresentar a situação e confirmar orientações e disponibilidade." },
      { question: "O tratamento para alcoolismo tem resultado garantido?", answer: "Não. Nenhum cuidado responsável deve prometer resultado. A evolução varia conforme múltiplos fatores individuais." },
      { question: "Como começo a conversa?", answer: "Basta ligar ou enviar a mensagem inicial pelo WhatsApp. A equipe fará perguntas para compreender o contexto." },
    ],
  },
  {
    slug: "jaboticabal-sp",
    name: "Jaboticabal",
    preposition: "de",
    intro: "Famílias de Jaboticabal podem se sentir divididas entre esperar uma mudança e procurar ajuda. Obter informações sobre acolhimento é um passo que pode ser dado sem decisões antecipadas.",
    localHeading: "Apoio informativo para quem está em Jaboticabal",
    localContext: "A Central está instalada em Araraquara e não possui unidade em Jaboticabal. A equipe conversa com famílias da região para verificar se a proposta de acolhimento pode ser avaliada.",
    welcomeHeading: "Acolhimento não é uma resposta automática",
    welcomeText: "A situação precisa ser compreendida e a família deve conhecer limites e responsabilidades. Somente depois dessa conversa é possível saber se há condições para os próximos passos.",
    dependencyHeading: "Dependência química e repetição de prejuízos",
    dependencyText: "Mesmo quando a pessoa tenta interromper o uso, padrões podem se repetir. O cuidado considera essas tentativas, o contexto atual e as necessidades que aparecem no relato.",
    alcoholHeading: "O alcoolismo e seus efeitos nos vínculos",
    alcoholText: "O consumo problemático pode afetar confiança e convivência. A orientação ajuda a família a falar sobre fatos e conhecer possibilidades sem estigmatizar a pessoa.",
    familyHeading: "Família informada participa melhor do processo",
    familyText: "Compreender etapas e condições permite uma participação mais consciente. A equipe responde às perguntas e evita criar expectativas que não possam ser confirmadas.",
    contactHeading: "Converse com a Central desde Jaboticabal",
    contactText: "O primeiro atendimento ocorre por telefone ou WhatsApp. A localização em Araraquara e os possíveis procedimentos são apresentados com antecedência.",
    seoDescription: "Informações para famílias de Jaboticabal sobre dependência química, alcoolismo e acolhimento na unidade da Central em Araraquara.",
    relatedSlugs: ["taquaritinga-sp", "ribeirao-preto-sp"],
    faqs: [
      { question: "A Central tem clínica em Jaboticabal?", answer: "Não. A unidade física fica em Araraquara. Famílias de Jaboticabal podem consultar o atendimento realizado nessa unidade." },
      { question: "Buscar informação compromete a família com o acolhimento?", answer: "Não. O contato inicial é orientativo e serve para esclarecer dúvidas e avaliar possibilidades." },
      { question: "Como falar com alguém que recusa ajuda?", answer: "Evite confronto em momentos de risco e procure orientação. Cada caso exige cuidado; não há uma abordagem única que garanta aceitação." },
      { question: "A internação involuntária pode ser decidida pela família sozinha?", answer: "Não. Essa modalidade exige critérios legais e profissionais aplicáveis e nunca deve ser realizada por conta própria." },
    ],
  },
  {
    slug: "franca-sp",
    name: "Franca",
    preposition: "de",
    intro: "Quem está em Franca e considera uma alternativa de acolhimento fora da cidade precisa de informações objetivas. A Central explica como funciona sua unidade de Araraquara antes de qualquer planejamento.",
    localHeading: "Orientação para famílias de Franca",
    localContext: "A Central de Acolhimento e Reabilitação não possui estrutura física em Franca. A unidade está em Araraquara e pode analisar contatos de outras localidades conforme avaliação, disponibilidade e condições.",
    welcomeHeading: "Avaliar com antecedência uma unidade em outra cidade",
    welcomeText: "A conversa inicial permite conhecer o processo sem deslocamento. A família apresenta suas dúvidas e recebe informações para decidir se faz sentido continuar a avaliação.",
    dependencyHeading: "Dependência química: cuidado além da interrupção do uso",
    dependencyText: "O problema pode envolver emoções, relações e organização da vida. Por isso, a proposta de cuidado precisa considerar diferentes aspectos e não pode se resumir a uma promessa rápida.",
    alcoholHeading: "Orientação quando o álcool causa perdas recorrentes",
    alcoholText: "A família pode perceber impactos antes que a própria pessoa reconheça o problema. O contato ajuda a entender possibilidades e limites, sem assegurar uma indicação antes da avaliação.",
    familyHeading: "Decidir com clareza mesmo à distância",
    familyText: "Moradores de Franca podem perguntar sobre cada etapa, localização e procedimentos. A transparência é essencial quando a opção considerada fica em outro município.",
    contactHeading: "Atendimento inicial para Franca",
    contactText: "Ligue ou envie mensagem para a Central. Se a situação puder seguir para avaliação, a equipe orientará como organizar os próximos passos em relação à unidade de Araraquara.",
    seoDescription: "Orientação a famílias de Franca que buscam informações sobre acolhimento para dependência química e alcoolismo na Central em Araraquara.",
    relatedSlugs: ["ribeirao-preto-sp", "jaboticabal-sp"],
    faqs: [
      { question: "Existe unidade da Central em Franca?", answer: "Não. A Central possui unidade física em Araraquara. O contato de Franca serve para consultar essa possibilidade de acolhimento." },
      { question: "Como avaliar o atendimento à distância?", answer: "Comece pelo telefone ou WhatsApp, faça perguntas sobre o processo e só organize qualquer deslocamento depois de receber as orientações necessárias." },
      { question: "A dependência química tem solução garantida?", answer: "Não existe garantia de resultado. O cuidado é individual e a evolução depende de diversos fatores." },
      { question: "A Central recebe pessoas de cidades mais distantes?", answer: "A equipe pode avaliar contatos de diferentes cidades, mas toda possibilidade depende do caso, da disponibilidade e das condições do acolhimento." },
    ],
  },
];

export const cityPageBySlug = Object.fromEntries(cityPages.map((city) => [city.slug, city])) as Record<
  string,
  CityPageData
>;