import { createFileRoute } from "@tanstack/react-router";
import { InstitutionalPage } from "@/components/institutional-page";
import { institutionalHead, institutionalIdentity, legalSources } from "@/lib/institutional";
import { emailDisplay, emailHref } from "@/lib/site";

export const Route = createFileRoute("/politica-de-privacidade")({
  staticData: { sitemap: true },
  head: () => institutionalHead("/politica-de-privacidade", "Política de Privacidade e LGPD", "Informações sobre dados pessoais, assistente virtual, orientação à família, serviços externos e solicitações de privacidade na Central."),
  component: PrivacyPage,
});

function PrivacyPage() {
  return <InstitutionalPage title="Política de Privacidade e LGPD" intro="Esta página descreve o funcionamento conhecido do site e os pontos que ainda dependem de confirmação institucional; não é uma certificação de conformidade com a LGPD.">
    <section><h2>Identificação e canal de privacidade</h2><p>Site da {institutionalIdentity.publicName}, CNPJ informado {institutionalIdentity.cnpj}. Razão social completa, endereço do controlador e eventual encarregado de dados aguardam confirmação. Solicitações de privacidade podem ser encaminhadas ao contato institucional <a href={emailHref}>{emailDisplay}</a>; esse contato não é apresentado como encarregado formalmente designado.</p></section>
    <section><h2>Orientação à família e assistente virtual</h2><p>As respostas do Guia de Orientação à Família ficam apenas na memória da página e são descartadas ao reiniciar o guia ou recarregar a página. O guia não envia essas escolhas para processamento externo.</p><p>Ao enviar uma mensagem ao Assistente de Acolhimento, o texto é transmitido ao serviço de inteligência artificial utilizado pelo site para produzir uma resposta. O histórico é temporário na interface; o site não mantém um cadastro das conversas. Isso não significa ausência de registros técnicos por parte da hospedagem e dos fornecedores envolvidos.</p><p>Não informe CPF, documentos, prontuários, endereço, dados de terceiros ou detalhes de saúde que identifiquem uma pessoa. Dados de saúde são sensíveis. O assistente é educativo, não realiza diagnóstico e não deve ser utilizado em emergências.</p></section>
    <section><h2>Contatos e serviços externos</h2><p>Ao escolher telefone, e-mail ou WhatsApp, você passa a utilizar o canal correspondente e pode fornecer dados diretamente durante o atendimento. Esses canais e os sites externos acessados por links possuem suas próprias práticas de privacidade. Links externos só devem ser usados se você concordar em acessar o respectivo serviço.</p><p>O site carrega fontes externas e pode gerar requisições técnicas que incluem endereço IP e informações do navegador. Serviços de hospedagem, segurança e diagnóstico podem tratar dados técnicos necessários à entrega do site.</p></section>
    <section><h2>Armazenamento, finalidade e limites</h2><p>O guia não grava respostas em armazenamento persistente do navegador. Não foram identificados no código editorial do site scripts próprios de Google Analytics ou Meta Pixel; isso não garante que a hospedagem não produza métricas ou registros técnicos.</p><p>As finalidades de atendimento pelos canais oficiais incluem responder dúvidas e receber solicitações. As bases legais, os prazos de retenção, os destinatários, eventuais transferências internacionais e as rotinas de exclusão dos dados de atendimento e dos fornecedores ainda precisam de confirmação documental da instituição. Não declaramos que toda operação depende de consentimento nem prometemos prazo de exclusão não confirmado.</p></section>
    <section><h2>Seus direitos</h2><p>Nos termos da LGPD e conforme o caso, você pode solicitar confirmação de tratamento, acesso, correção, informações sobre compartilhamento, anonimização, bloqueio ou eliminação de dados tratados irregularmente, portabilidade quando regulamentada e revogação do consentimento quando essa for a base legal. Existem exceções legais de conservação e requisitos de verificação de identidade.</p><p>Encaminhe sua solicitação para <a href={emailHref}>{emailDisplay}</a>, sem anexar documentos sensíveis de início. O canal deve orientar os dados estritamente necessários para verificar e atender o pedido.</p><p><a href={legalSources[2].href} target="_blank" rel="noopener noreferrer">Leia a LGPD — Lei 13.709/2018, texto oficial</a>.</p></section>
  </InstitutionalPage>;
}