import { createFileRoute } from "@tanstack/react-router";
import { InstitutionalPage } from "@/components/institutional-page";
import { TechnicalResponsibility } from "@/components/technical-responsibility";
import { InstitutionalLocation } from "@/components/institutional-location";
import { institutionalHead, institutionalIdentity, institutionalLocalBusiness, legalSources } from "@/lib/institutional";
import { emailDisplay, emailHref } from "@/lib/site";

export const Route = createFileRoute("/transparencia")({
  staticData: { sitemap: true },
  head: () => institutionalHead("/transparencia", "Transparência e Responsabilidade Técnica", "Equipe e localização da Central: R. Alfredo Micelli, 70, Condomínio Satélite, Araraquara/SP. Responsabilidade técnica e referências legais."),
  component: TransparencyPage,
});

function TransparencyPage() {
  return <InstitutionalPage title="Transparência e Responsabilidade Técnica" intro="Informações disponíveis, limites de comprovação e referências para decisões responsáveis sobre acolhimento e cuidado.">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(institutionalLocalBusiness).replace(/</g, "\\u003c") }} />
    <section><h2>Identificação institucional e localização</h2><p>Nome utilizado neste site: {institutionalIdentity.publicName}.</p><p><strong>Empresa / Titular:</strong> {institutionalIdentity.legalName}<br /><strong>CNPJ:</strong> {institutionalIdentity.cnpj}</p><p>Os dados empresariais foram fornecidos pela instituição; sua apresentação não substitui a consulta cadastral oficial nem comprova autorização sanitária. A única unidade física da Central fica em Araraquara/SP; páginas de outras cidades são informativas e não representam filiais.</p><InstitutionalLocation /></section>
    <section><h2>Responsabilidade técnica e gestão</h2><TechnicalResponsibility /><p className="mt-5 text-sm text-muted-foreground">Dados confirmados pela instituição. Os ícones verdes identificam os responsáveis apresentados e não representam validação independente por conselho profissional ou órgão sanitário.</p><p>Responsável Técnico Médico, CRM e UF permanecem não informados. A identificação dos responsáveis não implica revisão clínica dos artigos publicados.</p></section>
    <section><h2>Vigilância Sanitária e enquadramento do serviço</h2><p>{institutionalIdentity.sanitaryStatement}</p><p>Essa informação é uma declaração institucional, não uma certificação independente. Número, órgão emissor e validade da licença sanitária ainda aguardam confirmação documental. Não se declara habilitação hospitalar ou autorização para internação médica.</p><p>Antes de decidir, solicite à instituição a identificação cadastral, o endereço, a documentação aplicável e a identificação dos responsáveis pelo atendimento.</p></section>
    <section><h2>Acolhimento, internação e direitos</h2><p>A Lei 10.216/2001 prevê direitos das pessoas com transtornos mentais e distingue internação voluntária, involuntária e compulsória. A internação psiquiátrica exige laudo médico circunstanciado; a involuntária deve ser comunicada ao Ministério Público em até 72 horas, nos termos da lei.</p><p>A Lei 13.840/2019 alterou a Lei 11.343/2006 quanto ao cuidado relacionado ao uso de drogas, com prioridade ao tratamento ambulatorial. A internação é medida excepcional, sujeita aos requisitos legais e à avaliação e autorização médicas, não à decisão automática de familiares ou de um assistente virtual.</p><p>Acolhimento em comunidade terapêutica não equivale a internação hospitalar. A Lei 11.343/2006 veda qualquer modalidade de internação em comunidades terapêuticas acolhedoras e exige adesão e permanência voluntárias. A Central não anuncia aqui que realiza internação involuntária.</p><p>Esta orientação é educativa e não substitui avaliação clínica ou assessoria jurídica sobre um caso individual.</p></section>
    <section><h2>Fontes e responsabilidade editorial</h2><p>O conteúdo do site é institucional e educativo. Não há revisão clínica nominal confirmada; a informação não substitui atendimento profissional e não promete cura ou resultados.</p><ul>{legalSources.slice(0, 2).map(source => <li key={source.href}><a href={source.href} target="_blank" rel="noopener noreferrer">{source.label} — texto oficial</a></li>)}<li><a href="https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11343.htm" target="_blank" rel="noopener noreferrer">Lei 11.343/2006 — texto consolidado</a></li></ul></section>
    <section><h2>Manifestações e correções</h2><p>Para solicitar esclarecimentos, documentos ou correção de informações, escreva para <a href={emailHref}>{emailDisplay}</a>. Não há canal exclusivo de ouvidoria confirmado.</p></section>
  </InstitutionalPage>;
}