/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitySlugRouteImport } from './routes/$citySlug'
import { Route as AcolhimentoRouteImport } from './routes/acolhimento'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CidadesRouteImport } from './routes/cidades'
import { Route as ClinicaDeRecuperacaoEmAraraquaraRouteImport } from './routes/clinica-de-recuperacao-em-araraquara'
import { Route as ClinicaDeRecuperacaoEmSaoCarlosSpRouteImport } from './routes/clinica-de-recuperacao-em-sao-carlos-sp'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FamiliaRouteImport } from './routes/familia'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TratamentoRouteImport } from './routes/tratamento'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogDependenciaQuimicaEmAraraquaraTratamentoRouteImport } from './routes/blog.dependencia-quimica-em-araraquara-tratamento'
import { Route as BlogDependenciaQuimicaSaoCarlosRouteImport } from './routes/blog.dependencia-quimica-sao-carlos'
import { Route as BlogDependenciaQuimicaSinaisTratamentoRouteImport } from './routes/blog.dependencia-quimica-sinais-tratamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcolhimentoRoute = AcolhimentoRouteImport.update({
  id: '/acolhimento',
  path: '/acolhimento',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadesRoute = CidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaDeRecuperacaoEmAraraquaraRoute =
  ClinicaDeRecuperacaoEmAraraquaraRouteImport.update({
    id: '/clinica-de-recuperacao-em-araraquara',
    path: '/clinica-de-recuperacao-em-araraquara',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClinicaDeRecuperacaoEmSaoCarlosSpRoute =
  ClinicaDeRecuperacaoEmSaoCarlosSpRouteImport.update({
    id: '/clinica-de-recuperacao-em-sao-carlos-sp',
    path: '/clinica-de-recuperacao-em-sao-carlos-sp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaRoute = FamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentoRoute = TratamentoRouteImport.update({
  id: '/tratamento',
  path: '/tratamento',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogDependenciaQuimicaEmAraraquaraTratamentoRoute =
  BlogDependenciaQuimicaEmAraraquaraTratamentoRouteImport.update({
    id: '/dependencia-quimica-em-araraquara-tratamento',
    path: '/dependencia-quimica-em-araraquara-tratamento',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDependenciaQuimicaSaoCarlosRoute =
  BlogDependenciaQuimicaSaoCarlosRouteImport.update({
    id: '/dependencia-quimica-sao-carlos',
    path: '/dependencia-quimica-sao-carlos',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDependenciaQuimicaSinaisTratamentoRoute =
  BlogDependenciaQuimicaSinaisTratamentoRouteImport.update({
    id: '/dependencia-quimica-sinais-tratamento',
    path: '/dependencia-quimica-sinais-tratamento',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRoute
  '/acolhimento': typeof AcolhimentoRoute
  '/blog': typeof BlogRouteWithChildren
  '/cidades': typeof CidadesRoute
  '/clinica-de-recuperacao-em-araraquara': typeof ClinicaDeRecuperacaoEmAraraquaraRoute
  '/clinica-de-recuperacao-em-sao-carlos-sp': typeof ClinicaDeRecuperacaoEmSaoCarlosSpRoute
  '/contato': typeof ContatoRoute
  '/familia': typeof FamiliaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tratamento': typeof TratamentoRoute
  '/videos': typeof VideosRoute
  '/blog/dependencia-quimica-em-araraquara-tratamento': typeof BlogDependenciaQuimicaEmAraraquaraTratamentoRoute
  '/blog/dependencia-quimica-sao-carlos': typeof BlogDependenciaQuimicaSaoCarlosRoute
  '/blog/dependencia-quimica-sinais-tratamento': typeof BlogDependenciaQuimicaSinaisTratamentoRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRoute
  '/acolhimento': typeof AcolhimentoRoute
  '/cidades': typeof CidadesRoute
  '/clinica-de-recuperacao-em-araraquara': typeof ClinicaDeRecuperacaoEmAraraquaraRoute
  '/clinica-de-recuperacao-em-sao-carlos-sp': typeof ClinicaDeRecuperacaoEmSaoCarlosSpRoute
  '/contato': typeof ContatoRoute
  '/familia': typeof FamiliaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tratamento': typeof TratamentoRoute
  '/videos': typeof VideosRoute
  '/blog/dependencia-quimica-em-araraquara-tratamento': typeof BlogDependenciaQuimicaEmAraraquaraTratamentoRoute
  '/blog/dependencia-quimica-sao-carlos': typeof BlogDependenciaQuimicaSaoCarlosRoute
  '/blog/dependencia-quimica-sinais-tratamento': typeof BlogDependenciaQuimicaSinaisTratamentoRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRoute
  '/acolhimento': typeof AcolhimentoRoute
  '/blog': typeof BlogRouteWithChildren
  '/cidades': typeof CidadesRoute
  '/clinica-de-recuperacao-em-araraquara': typeof ClinicaDeRecuperacaoEmAraraquaraRoute
  '/clinica-de-recuperacao-em-sao-carlos-sp': typeof ClinicaDeRecuperacaoEmSaoCarlosSpRoute
  '/contato': typeof ContatoRoute
  '/familia': typeof FamiliaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tratamento': typeof TratamentoRoute
  '/videos': typeof VideosRoute
  '/blog/dependencia-quimica-em-araraquara-tratamento': typeof BlogDependenciaQuimicaEmAraraquaraTratamentoRoute
  '/blog/dependencia-quimica-sao-carlos': typeof BlogDependenciaQuimicaSaoCarlosRoute
  '/blog/dependencia-quimica-sinais-tratamento': typeof BlogDependenciaQuimicaSinaisTratamentoRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$citySlug'
    | '/acolhimento'
    | '/blog'
    | '/cidades'
    | '/clinica-de-recuperacao-em-araraquara'
    | '/clinica-de-recuperacao-em-sao-carlos-sp'
    | '/contato'
    | '/familia'
    | '/sitemap.xml'
    | '/tratamento'
    | '/videos'
    | '/blog/dependencia-quimica-em-araraquara-tratamento'
    | '/blog/dependencia-quimica-sao-carlos'
    | '/blog/dependencia-quimica-sinais-tratamento'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$citySlug'
    | '/acolhimento'
    | '/cidades'
    | '/clinica-de-recuperacao-em-araraquara'
    | '/clinica-de-recuperacao-em-sao-carlos-sp'
    | '/contato'
    | '/familia'
    | '/sitemap.xml'
    | '/tratamento'
    | '/videos'
    | '/blog/dependencia-quimica-em-araraquara-tratamento'
    | '/blog/dependencia-quimica-sao-carlos'
    | '/blog/dependencia-quimica-sinais-tratamento'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$citySlug'
    | '/acolhimento'
    | '/blog'
    | '/cidades'
    | '/clinica-de-recuperacao-em-araraquara'
    | '/clinica-de-recuperacao-em-sao-carlos-sp'
    | '/contato'
    | '/familia'
    | '/sitemap.xml'
    | '/tratamento'
    | '/videos'
    | '/blog/dependencia-quimica-em-araraquara-tratamento'
    | '/blog/dependencia-quimica-sao-carlos'
    | '/blog/dependencia-quimica-sinais-tratamento'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitySlugRoute: typeof CitySlugRoute
  AcolhimentoRoute: typeof AcolhimentoRoute
  BlogRoute: typeof BlogRouteWithChildren
  CidadesRoute: typeof CidadesRoute
  ClinicaDeRecuperacaoEmAraraquaraRoute: typeof ClinicaDeRecuperacaoEmAraraquaraRoute
  ClinicaDeRecuperacaoEmSaoCarlosSpRoute: typeof ClinicaDeRecuperacaoEmSaoCarlosSpRoute
  ContatoRoute: typeof ContatoRoute
  FamiliaRoute: typeof FamiliaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TratamentoRoute: typeof TratamentoRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug': {
      id: '/$citySlug'
      path: '/$citySlug'
      fullPath: '/$citySlug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acolhimento': {
      id: '/acolhimento'
      path: '/acolhimento'
      fullPath: '/acolhimento'
      preLoaderRoute: typeof AcolhimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidades': {
      id: '/cidades'
      path: '/cidades'
      fullPath: '/cidades'
      preLoaderRoute: typeof CidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica-de-recuperacao-em-araraquara': {
      id: '/clinica-de-recuperacao-em-araraquara'
      path: '/clinica-de-recuperacao-em-araraquara'
      fullPath: '/clinica-de-recuperacao-em-araraquara'
      preLoaderRoute: typeof ClinicaDeRecuperacaoEmAraraquaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica-de-recuperacao-em-sao-carlos-sp': {
      id: '/clinica-de-recuperacao-em-sao-carlos-sp'
      path: '/clinica-de-recuperacao-em-sao-carlos-sp'
      fullPath: '/clinica-de-recuperacao-em-sao-carlos-sp'
      preLoaderRoute: typeof ClinicaDeRecuperacaoEmSaoCarlosSpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia': {
      id: '/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof FamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamento': {
      id: '/tratamento'
      path: '/tratamento'
      fullPath: '/tratamento'
      preLoaderRoute: typeof TratamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/dependencia-quimica-em-araraquara-tratamento': {
      id: '/blog/dependencia-quimica-em-araraquara-tratamento'
      path: '/dependencia-quimica-em-araraquara-tratamento'
      fullPath: '/blog/dependencia-quimica-em-araraquara-tratamento'
      preLoaderRoute: typeof BlogDependenciaQuimicaEmAraraquaraTratamentoRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/dependencia-quimica-sao-carlos': {
      id: '/blog/dependencia-quimica-sao-carlos'
      path: '/dependencia-quimica-sao-carlos'
      fullPath: '/blog/dependencia-quimica-sao-carlos'
      preLoaderRoute: typeof BlogDependenciaQuimicaSaoCarlosRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/dependencia-quimica-sinais-tratamento': {
      id: '/blog/dependencia-quimica-sinais-tratamento'
      path: '/dependencia-quimica-sinais-tratamento'
      fullPath: '/blog/dependencia-quimica-sinais-tratamento'
      preLoaderRoute: typeof BlogDependenciaQuimicaSinaisTratamentoRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogDependenciaQuimicaEmAraraquaraTratamentoRoute: typeof BlogDependenciaQuimicaEmAraraquaraTratamentoRoute
  BlogDependenciaQuimicaSaoCarlosRoute: typeof BlogDependenciaQuimicaSaoCarlosRoute
  BlogDependenciaQuimicaSinaisTratamentoRoute: typeof BlogDependenciaQuimicaSinaisTratamentoRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogDependenciaQuimicaEmAraraquaraTratamentoRoute:
    BlogDependenciaQuimicaEmAraraquaraTratamentoRoute,
  BlogDependenciaQuimicaSaoCarlosRoute: BlogDependenciaQuimicaSaoCarlosRoute,
  BlogDependenciaQuimicaSinaisTratamentoRoute:
    BlogDependenciaQuimicaSinaisTratamentoRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitySlugRoute: CitySlugRoute,
  AcolhimentoRoute: AcolhimentoRoute,
  BlogRoute: BlogRouteWithChildren,
  CidadesRoute: CidadesRoute,
  ClinicaDeRecuperacaoEmAraraquaraRoute: ClinicaDeRecuperacaoEmAraraquaraRoute,
  ClinicaDeRecuperacaoEmSaoCarlosSpRoute:
    ClinicaDeRecuperacaoEmSaoCarlosSpRoute,
  ContatoRoute: ContatoRoute,
  FamiliaRoute: FamiliaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TratamentoRoute: TratamentoRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
