/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CidadesRouteImport } from './routes/cidades'
import { Route as ClinicaDeRecuperacaoEmAraraquaraRouteImport } from './routes/clinica-de-recuperacao-em-araraquara'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadesRoute = CidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaDeRecuperacaoEmAraraquaraRoute =
  ClinicaDeRecuperacaoEmAraraquaraRouteImport.update({
    id: '/clinica-de-recuperacao-em-araraquara',
    path: '/clinica-de-recuperacao-em-araraquara',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cidades': typeof CidadesRoute
  '/clinica-de-recuperacao-em-araraquara': typeof ClinicaDeRecuperacaoEmAraraquaraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cidades': typeof CidadesRoute
  '/clinica-de-recuperacao-em-araraquara': typeof ClinicaDeRecuperacaoEmAraraquaraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cidades': typeof CidadesRoute
  '/clinica-de-recuperacao-em-araraquara': typeof ClinicaDeRecuperacaoEmAraraquaraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/blog' | '/cidades' | '/clinica-de-recuperacao-em-araraquara'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/cidades' | '/clinica-de-recuperacao-em-araraquara'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cidades'
    | '/clinica-de-recuperacao-em-araraquara'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CidadesRoute: typeof CidadesRoute
  ClinicaDeRecuperacaoEmAraraquaraRoute: typeof ClinicaDeRecuperacaoEmAraraquaraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidades': {
      id: '/cidades'
      path: '/cidades'
      fullPath: '/cidades'
      preLoaderRoute: typeof CidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica-de-recuperacao-em-araraquara': {
      id: '/clinica-de-recuperacao-em-araraquara'
      path: '/clinica-de-recuperacao-em-araraquara'
      fullPath: '/clinica-de-recuperacao-em-araraquara'
      preLoaderRoute: typeof ClinicaDeRecuperacaoEmAraraquaraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CidadesRoute: CidadesRoute,
  ClinicaDeRecuperacaoEmAraraquaraRoute: ClinicaDeRecuperacaoEmAraraquaraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
